### ISSUE TITLE
More actions not downloading

### ISSUE THREAD

**Issue by tobimori** [atom0s/ElgatoLegacy#1]
Stays on "Downloading".

**Comment by atom0s** [comment]
Hello, this is a known issue and not something I am too concerned with fixing at the moment. But when I have more free time, I will take a look to see what is preventing it from loading.

**Comment by Rustyb0y** [comment]
By default if you try and install plugins that do not come with the software they will say the O/S is not supported.

In the JSON of the plugins it has this block.

  "OS": [
    {
      "Platform": "windows",
      "MinimumVersion": "10"
    }

You can change the version to your Windows 7 version, mine is 6.1.7601 and they will install.

**Comment by OfficiallySp** [comment]
how would you go about editing an already existing .streamdeckplugin file. trying to install the [audio mute plugin](https://github.com/fredemmott/StreamDeck-AudioMute) and cannot seem to get into the files and edit it

**Comment by Rustyb0y** [comment]
I opened the plugin file in 7zip, then edited and saved it inside 7zip.

**Comment by ASKemp** [comment]
Some guidance on downloading/installing plugins would be gratefully accepted! :)

**Comment by atom0s** [comment]
This is now fixed in the latest release v1.0.0.2! :) 

https://github.com/atom0s/ElgatoLegacy/releases/latest
