### ISSUE TITLE
Keys not working

### ISSUE THREAD

**Issue by thaboy1992** [atom0s/ElgatoLegacy#2]
Hi,

Software installed: Yes and working
Hardware installed: Yes and LCD keys are getting data from the software so thats okay.

The only issue i have is, when i press a LCD button, nothing happens.

Did you had the same problem?

OS: Win 7 64-bit

**Comment by Rustyb0y** [comment]
Yes, I have the same issue.

OBS Reporting the Plugin working
The Elgato Stream Deck is connected and can see OBS.

Pressing the buttons does nothing

**Comment by Rustyb0y** [comment]
After a few checks it seems Elgato Stream Deck will not work on windows 7 due to certain o/s components missing.  It will work on 8 and 8.1 though.

**Comment by atom0s** [comment]
Hello guys, thanks for the report. I am looking into this currently.

For Windows 7 there appears to be a failure while calling one of the service level APIs, in this case:
 - WTSGetActiveConsoleSessionId
 - WTSQuerySessionInformationW

The StreamDeck software is checking the current session information with the 'WTSSessionInfoEx' flag here for some reason and this is landing up returning bad data causing the function using it to return a bad value. This return causes the StreamDeck to skip over processing the grid key press. (Pressing a button on the deck.)

I am not familiar with this API so I am looking into this a bit more before I opt. to just patch the given function as needed to bypass this check. But, I am able to make the deck fully work on Windows 7 by adjusting the program to ignore what this API is doing. So I will hopefully have something posted in the near future to fix this for Windows 7.

**Comment by thaboy1992** [comment]
Lazy software engeneers...


The applications i build for my clients still work on xp   haha

Op ma 27 apr. 2020 06:16 schreef Rustyb0y <notifications@github.com>:

**Comment by atom0s** [comment]
If any other developer runs into this issue, it appears this is a known bug to Microsoft, yay..

> Windows Server 2008 R2 and Windows 7:  Due to a code defect, the usage of the WTS_SESSIONSTATE_LOCK and WTS_SESSIONSTATE_UNLOCK flags is reversed. That is, WTS_SESSIONSTATE_LOCK indicates that the session is unlocked, and WTS_SESSIONSTATE_UNLOCK indicates the session is locked.

**Comment by thaboy1992** [comment]
I hope you can fix it.  Big ShoutOut to you.  You can help a lot of people
with this.

Op ma 27 apr. 2020 07:57 schreef atom0s <notifications@github.com>:

**Comment by atom0s** [comment]
This is now fixed in the latest release. :) v1.0.0.1
https://github.com/atom0s/ElgatoLegacy/releases/latest
