### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by Tonybologna69** [atom0s/ElgatoLegacy#3]
The provided instructions are incorrect on step 2 of installing the Elgato Legacy DLLs. It says:

" 1 - Open the Elgato folder located at: C:\Elgato\extracted\Elgato\
2 - Drag and drop the files from the ElgatoLegacy zip file into the Elgato folder."

The correct path is "C:\Elgato\extracted\Elgato\StreamDeck"

**Comment by ASKemp** [comment]
Just came to say the same thing.

**Comment by atom0s** [comment]
Thanks for the heads up, should be fixed now.
