### ISSUE TITLE
v.1.0.0.3 - Can No Longer Open Certain File Extensions

### ISSUE THREAD

**Issue by Preroll5** [atom0s/ElgatoLegacy#5]
I am sending a note in regards to the recent release of Legacy v.1.0.0.3.  I am not a developer nor can I debug the code but just noting an observation.  When using v.1.0.0.1, all functions worked on the Stream Deck minus the “More Actions” to acquire additional plugins.  With v.1.0.0.3, it does in fact now work for “More Actions” and I’m able to download additional plugins.  However, I noticed an anomaly in that certain files can no longer be opened.  I have a lot of shortcuts to files within the Windows – System32  folder.  For example, HDWWIZ.CPL is the Device Manager which I use quite frequently.  I had a file open command to launch that.  It used to work.  I also noticed that other apps will no longer launch that end in .msc.  So something in v.1.0.0.3 has broken the ability to open files with a .cpl or .msc extension (maybe others too but not sure).  To test this, I put back v.1.0.0.1 and they all launched without issue but of course this took away the ability to use the ‘More Actions’ button to acquire plugins again.  So basically, I use v.1.0.0.3 to get plugins, and then switch it back to v.1.0.0.1 to regain functionality for launching files with .cpl and .msc extensions

Just wanted to point this out in case you may have an idea why v.1.0.0.3 may have impeded this function.

Thank you.

**Comment by atom0s** [comment]
This does not sound related to this project. Especially if the DLLs are only in the folder with SteamDeck and not placed in the system folder. _(You shouldn't be putting these DLLs anywhere else other than with SteamDeck in a separate folder.)_

**Comment by Preroll5** [comment]
Thanks for reviewing.  Just a quick reply.  The DLL's are in fact within the StreamDeck folder.  The issue is that the DLL's supplied with v.1.0.0.3 impedes the ability to do an OPEN command with files that contain CPL or MSC extensions.  The OPEN command works fine for all other files and apps.  If I were to revert the DLL's (within the StreamDeck folder) back to v.1.0.0.1, then the OPEN command does in fact work with ALL file extensions.  Thinking there may have been some confusion in my original post.  Thanks again.
