### ISSUE TITLE
XSplit Support

### ISSUE THREAD

**Issue by Kedarius** [atom0s/ElgatoLegacy#6]
Firstly, let me thank you for a great little tool. I am finally able to use my streamdeck on my Win 8.1 work computer.
However main reason for buying streamdeck was controlling XSplit Broadcaster... And that is still problem even with ElgatoLegacy. I am able to run stream deck SW, install xsplit plugin into it but I am not able to install streamdeck plugin into xsplit. It does detect that I am not running Win10 and refuses to install the plugin. I tried to copy your dlls to xsplit directory, but it did not help. 

Have anyone got it working? Or any ideas that I could try?

**Comment by atom0s** [comment]
This project is not aimed at or targeted for other software other than Elgato's StreamDeck software itself.
